/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_markdown_marker = 2,
  sym_markdown_lang = 3,
  aux_sym_markdown_line_token1 = 4,
  sym_code_marker = 5,
  sym_language = 6,
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 7,
  sym_source_file = 8,
  sym_cell = 9,
  sym_markdown_cell = 10,
  sym_markdown_line = 11,
  sym_code_cell = 12,
  sym_code_line = 13,
  sym_fenced_code_cell = 14,
  sym_fence_start = 15,
  sym_fence_end = 16,
  sym_fenced_line = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_markdown_cell_repeat1 = 19,
  aux_sym_code_cell_repeat1 = 20,
  aux_sym_fenced_code_cell_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_markdown_marker] = "markdown_marker",
  [sym_markdown_lang] = "markdown_lang",
  [aux_sym_markdown_line_token1] = "markdown_line_token1",
  [sym_code_marker] = "code_marker",
  [sym_language] = "language",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "```",
  [sym_source_file] = "source_file",
  [sym_cell] = "cell",
  [sym_markdown_cell] = "markdown_cell",
  [sym_markdown_line] = "markdown_line",
  [sym_code_cell] = "code_cell",
  [sym_code_line] = "code_line",
  [sym_fenced_code_cell] = "fenced_code_cell",
  [sym_fence_start] = "fence_start",
  [sym_fence_end] = "fence_end",
  [sym_fenced_line] = "fenced_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_markdown_cell_repeat1] = "markdown_cell_repeat1",
  [aux_sym_code_cell_repeat1] = "code_cell_repeat1",
  [aux_sym_fenced_code_cell_repeat1] = "fenced_code_cell_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_markdown_marker] = sym_markdown_marker,
  [sym_markdown_lang] = sym_markdown_lang,
  [aux_sym_markdown_line_token1] = aux_sym_markdown_line_token1,
  [sym_code_marker] = sym_code_marker,
  [sym_language] = sym_language,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [sym_source_file] = sym_source_file,
  [sym_cell] = sym_cell,
  [sym_markdown_cell] = sym_markdown_cell,
  [sym_markdown_line] = sym_markdown_line,
  [sym_code_cell] = sym_code_cell,
  [sym_code_line] = sym_code_line,
  [sym_fenced_code_cell] = sym_fenced_code_cell,
  [sym_fence_start] = sym_fence_start,
  [sym_fence_end] = sym_fence_end,
  [sym_fenced_line] = sym_fenced_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_markdown_cell_repeat1] = aux_sym_markdown_cell_repeat1,
  [aux_sym_code_cell_repeat1] = aux_sym_code_cell_repeat1,
  [aux_sym_fenced_code_cell_repeat1] = aux_sym_fenced_code_cell_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_markdown_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_lang] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_markdown_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_code_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_language] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_line] = {
    .visible = true,
    .named = true,
  },
  [sym_code_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_code_line] = {
    .visible = true,
    .named = true,
  },
  [sym_fenced_code_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_start] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_end] = {
    .visible = true,
    .named = true,
  },
  [sym_fenced_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markdown_cell_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_cell_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fenced_code_cell_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_fence_end = 1,
  field_fence_start = 2,
  field_lang = 3,
  field_marker = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_fence_end] = "fence_end",
  [field_fence_start] = "fence_start",
  [field_lang] = "lang",
  [field_marker] = "marker",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_marker, 0},
  [1] =
    {field_lang, 1},
    {field_marker, 0},
  [3] =
    {field_fence_end, 2},
    {field_fence_start, 0},
  [5] =
    {field_fence_end, 3},
    {field_fence_start, 0},
  [7] =
    {field_fence_end, 3},
    {field_fence_start, 0},
    {field_lang, 1},
  [10] =
    {field_fence_end, 4},
    {field_fence_start, 0},
    {field_lang, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == '`') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '`') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '[') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '[') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == '`') ADVANCE(42);
      END_STATE();
    case 7:
      if (lookahead == '`') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'k') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(33);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 12:
      if (lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'w') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '\n') SKIP(18);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '`') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_markdown_marker);
      if (lookahead == '%') ADVANCE(30);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_markdown_marker);
      if (lookahead == '%') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_markdown_lang);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_markdown_line_token1);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '`') ADVANCE(28);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(29);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_markdown_line_token1);
      if (lookahead == '%') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_markdown_line_token1);
      if (lookahead == '`') ADVANCE(28);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_markdown_line_token1);
      if (lookahead == '`') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_markdown_line_token1);
      if (lookahead == '`') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_markdown_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_code_marker);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_code_marker);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_language);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == 'a') ADVANCE(38);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == 'd') ADVANCE(37);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == 'k') ADVANCE(34);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == 'n') ADVANCE(41);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == 'o') ADVANCE(39);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == 'r') ADVANCE(35);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == 'w') ADVANCE(36);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == ']') ADVANCE(23);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 18},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 18},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_markdown_marker] = ACTIONS(1),
    [sym_markdown_lang] = ACTIONS(1),
    [sym_code_marker] = ACTIONS(1),
    [sym_language] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(35),
    [sym_cell] = STATE(2),
    [sym_markdown_cell] = STATE(20),
    [sym_code_cell] = STATE(20),
    [sym_fenced_code_cell] = STATE(20),
    [sym_fence_start] = STATE(28),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_markdown_marker] = ACTIONS(5),
    [sym_code_marker] = ACTIONS(7),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      sym_markdown_marker,
    ACTIONS(7), 1,
      sym_code_marker,
    ACTIONS(9), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      sym_fence_start,
    STATE(3), 2,
      sym_cell,
      aux_sym_source_file_repeat1,
    STATE(20), 3,
      sym_markdown_cell,
      sym_code_cell,
      sym_fenced_code_cell,
  [25] = 7,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_markdown_marker,
    ACTIONS(18), 1,
      sym_code_marker,
    ACTIONS(21), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(28), 1,
      sym_fence_start,
    STATE(3), 2,
      sym_cell,
      aux_sym_source_file_repeat1,
    STATE(20), 3,
      sym_markdown_cell,
      sym_code_cell,
      sym_fenced_code_cell,
  [50] = 4,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 1,
      aux_sym_markdown_line_token1,
    STATE(12), 2,
      sym_markdown_line,
      aux_sym_markdown_cell_repeat1,
    ACTIONS(26), 3,
      sym_markdown_marker,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [66] = 4,
    ACTIONS(28), 1,
      aux_sym_markdown_line_token1,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
    STATE(12), 2,
      sym_markdown_line,
      aux_sym_markdown_cell_repeat1,
    ACTIONS(32), 3,
      sym_markdown_marker,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [82] = 4,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      aux_sym_markdown_line_token1,
    STATE(9), 2,
      sym_code_line,
      aux_sym_code_cell_repeat1,
    ACTIONS(36), 3,
      sym_markdown_marker,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [98] = 4,
    ACTIONS(28), 1,
      aux_sym_markdown_line_token1,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    STATE(5), 2,
      sym_markdown_line,
      aux_sym_markdown_cell_repeat1,
    ACTIONS(42), 3,
      sym_markdown_marker,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [114] = 4,
    ACTIONS(28), 1,
      aux_sym_markdown_line_token1,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(4), 2,
      sym_markdown_line,
      aux_sym_markdown_cell_repeat1,
    ACTIONS(46), 3,
      sym_markdown_marker,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [130] = 4,
    ACTIONS(38), 1,
      aux_sym_markdown_line_token1,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    STATE(11), 2,
      sym_code_line,
      aux_sym_code_cell_repeat1,
    ACTIONS(50), 3,
      sym_markdown_marker,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [146] = 4,
    ACTIONS(38), 1,
      aux_sym_markdown_line_token1,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    STATE(13), 2,
      sym_code_line,
      aux_sym_code_cell_repeat1,
    ACTIONS(54), 3,
      sym_markdown_marker,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [162] = 4,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      aux_sym_markdown_line_token1,
    STATE(11), 2,
      sym_code_line,
      aux_sym_code_cell_repeat1,
    ACTIONS(58), 3,
      sym_markdown_marker,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [178] = 4,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      aux_sym_markdown_line_token1,
    STATE(12), 2,
      sym_markdown_line,
      aux_sym_markdown_cell_repeat1,
    ACTIONS(65), 3,
      sym_markdown_marker,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [194] = 4,
    ACTIONS(38), 1,
      aux_sym_markdown_line_token1,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    STATE(11), 2,
      sym_code_line,
      aux_sym_code_cell_repeat1,
    ACTIONS(72), 3,
      sym_markdown_marker,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [210] = 2,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 4,
      sym_markdown_marker,
      aux_sym_markdown_line_token1,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [220] = 4,
    ACTIONS(78), 1,
      aux_sym_markdown_line_token1,
    ACTIONS(80), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(21), 1,
      sym_fence_end,
    STATE(17), 2,
      sym_fenced_line,
      aux_sym_fenced_code_cell_repeat1,
  [234] = 2,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 4,
      sym_markdown_marker,
      aux_sym_markdown_line_token1,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [244] = 4,
    ACTIONS(78), 1,
      aux_sym_markdown_line_token1,
    ACTIONS(80), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(24), 1,
      sym_fence_end,
    STATE(23), 2,
      sym_fenced_line,
      aux_sym_fenced_code_cell_repeat1,
  [258] = 4,
    ACTIONS(78), 1,
      aux_sym_markdown_line_token1,
    ACTIONS(80), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(25), 1,
      sym_fence_end,
    STATE(19), 2,
      sym_fenced_line,
      aux_sym_fenced_code_cell_repeat1,
  [272] = 4,
    ACTIONS(78), 1,
      aux_sym_markdown_line_token1,
    ACTIONS(80), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(26), 1,
      sym_fence_end,
    STATE(23), 2,
      sym_fenced_line,
      aux_sym_fenced_code_cell_repeat1,
  [286] = 2,
    ACTIONS(88), 1,
      sym_markdown_marker,
    ACTIONS(86), 3,
      ts_builtin_sym_end,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [295] = 2,
    ACTIONS(92), 1,
      sym_markdown_marker,
    ACTIONS(90), 3,
      ts_builtin_sym_end,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [304] = 2,
    ACTIONS(96), 1,
      sym_markdown_marker,
    ACTIONS(94), 3,
      ts_builtin_sym_end,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [313] = 3,
    ACTIONS(98), 1,
      aux_sym_markdown_line_token1,
    ACTIONS(101), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(23), 2,
      sym_fenced_line,
      aux_sym_fenced_code_cell_repeat1,
  [324] = 2,
    ACTIONS(105), 1,
      sym_markdown_marker,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [333] = 2,
    ACTIONS(109), 1,
      sym_markdown_marker,
    ACTIONS(107), 3,
      ts_builtin_sym_end,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [342] = 2,
    ACTIONS(113), 1,
      sym_markdown_marker,
    ACTIONS(111), 3,
      ts_builtin_sym_end,
      sym_code_marker,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [351] = 2,
    ACTIONS(115), 1,
      anon_sym_LF,
    ACTIONS(117), 1,
      sym_markdown_lang,
  [358] = 2,
    ACTIONS(119), 1,
      anon_sym_LF,
    ACTIONS(121), 1,
      sym_language,
  [365] = 2,
    ACTIONS(123), 1,
      anon_sym_LF,
    ACTIONS(125), 1,
      sym_language,
  [372] = 1,
    ACTIONS(127), 2,
      aux_sym_markdown_line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [377] = 2,
    ACTIONS(129), 1,
      anon_sym_LF,
    ACTIONS(131), 1,
      sym_language,
  [384] = 1,
    ACTIONS(133), 1,
      anon_sym_LF,
  [388] = 1,
    ACTIONS(135), 1,
      anon_sym_LF,
  [392] = 1,
    ACTIONS(137), 1,
      anon_sym_LF,
  [396] = 1,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 66,
  [SMALL_STATE(6)] = 82,
  [SMALL_STATE(7)] = 98,
  [SMALL_STATE(8)] = 114,
  [SMALL_STATE(9)] = 130,
  [SMALL_STATE(10)] = 146,
  [SMALL_STATE(11)] = 162,
  [SMALL_STATE(12)] = 178,
  [SMALL_STATE(13)] = 194,
  [SMALL_STATE(14)] = 210,
  [SMALL_STATE(15)] = 220,
  [SMALL_STATE(16)] = 234,
  [SMALL_STATE(17)] = 244,
  [SMALL_STATE(18)] = 258,
  [SMALL_STATE(19)] = 272,
  [SMALL_STATE(20)] = 286,
  [SMALL_STATE(21)] = 295,
  [SMALL_STATE(22)] = 304,
  [SMALL_STATE(23)] = 313,
  [SMALL_STATE(24)] = 324,
  [SMALL_STATE(25)] = 333,
  [SMALL_STATE(26)] = 342,
  [SMALL_STATE(27)] = 351,
  [SMALL_STATE(28)] = 358,
  [SMALL_STATE(29)] = 365,
  [SMALL_STATE(30)] = 372,
  [SMALL_STATE(31)] = 377,
  [SMALL_STATE(32)] = 384,
  [SMALL_STATE(33)] = 388,
  [SMALL_STATE(34)] = 392,
  [SMALL_STATE(35)] = 396,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_cell, 4, 0, 2),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_cell, 4, 0, 2),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_cell, 3, 0, 1),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_cell, 3, 0, 1),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_cell, 2, 0, 1),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_cell, 2, 0, 1),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_cell, 2, 0, 1),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_cell, 2, 0, 1),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_cell, 3, 0, 2),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_cell, 3, 0, 2),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_cell, 3, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_cell, 3, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_cell, 3, 0, 2),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_cell, 3, 0, 2),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_cell_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_cell_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_cell_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_markdown_cell_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_markdown_cell_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markdown_cell_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_cell, 4, 0, 2),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_cell, 4, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_line, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_line, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_line, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_line, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cell, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cell, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_cell, 3, 0, 3),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_cell, 3, 0, 3),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence_end, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence_end, 1, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fenced_code_cell_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_fenced_code_cell_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_cell, 4, 0, 4),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_cell, 4, 0, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_cell, 4, 0, 5),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_cell, 4, 0, 5),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_cell, 5, 0, 6),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_cell, 5, 0, 6),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_line, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence_start, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence_start, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [139] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fknb(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fknb",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
