/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND_PERCENT = 1,
  anon_sym_LF = 2,
  sym_language_markdown = 3,
  aux_sym_markdown_text_line_token1 = 4,
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 5,
  anon_sym_POUND_PERCENT_PERCENT = 6,
  sym_language_tag = 7,
  sym_source_file = 8,
  sym_notebook_cell = 9,
  sym_notebook_markdown_cell = 10,
  sym__markdown_block = 11,
  sym_markdown_text_line = 12,
  sym_markdown_fenced_block = 13,
  sym_notebook_code_cell = 14,
  sym_raw_code_line = 15,
  aux_sym_source_file_repeat1 = 16,
  aux_sym_notebook_markdown_cell_repeat1 = 17,
  aux_sym_markdown_fenced_block_repeat1 = 18,
  aux_sym_notebook_code_cell_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND_PERCENT] = "#%",
  [anon_sym_LF] = "\n",
  [sym_language_markdown] = "language_markdown",
  [aux_sym_markdown_text_line_token1] = "markdown_text_line_token1",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "```",
  [anon_sym_POUND_PERCENT_PERCENT] = "#%%",
  [sym_language_tag] = "language_tag",
  [sym_source_file] = "source_file",
  [sym_notebook_cell] = "notebook_cell",
  [sym_notebook_markdown_cell] = "notebook_markdown_cell",
  [sym__markdown_block] = "_markdown_block",
  [sym_markdown_text_line] = "markdown_text_line",
  [sym_markdown_fenced_block] = "markdown_fenced_block",
  [sym_notebook_code_cell] = "notebook_code_cell",
  [sym_raw_code_line] = "raw_code_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_notebook_markdown_cell_repeat1] = "notebook_markdown_cell_repeat1",
  [aux_sym_markdown_fenced_block_repeat1] = "markdown_fenced_block_repeat1",
  [aux_sym_notebook_code_cell_repeat1] = "notebook_code_cell_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND_PERCENT] = anon_sym_POUND_PERCENT,
  [anon_sym_LF] = anon_sym_LF,
  [sym_language_markdown] = sym_language_markdown,
  [aux_sym_markdown_text_line_token1] = aux_sym_markdown_text_line_token1,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [anon_sym_POUND_PERCENT_PERCENT] = anon_sym_POUND_PERCENT_PERCENT,
  [sym_language_tag] = sym_language_tag,
  [sym_source_file] = sym_source_file,
  [sym_notebook_cell] = sym_notebook_cell,
  [sym_notebook_markdown_cell] = sym_notebook_markdown_cell,
  [sym__markdown_block] = sym__markdown_block,
  [sym_markdown_text_line] = sym_markdown_text_line,
  [sym_markdown_fenced_block] = sym_markdown_fenced_block,
  [sym_notebook_code_cell] = sym_notebook_code_cell,
  [sym_raw_code_line] = sym_raw_code_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_notebook_markdown_cell_repeat1] = aux_sym_notebook_markdown_cell_repeat1,
  [aux_sym_markdown_fenced_block_repeat1] = aux_sym_markdown_fenced_block_repeat1,
  [aux_sym_notebook_code_cell_repeat1] = aux_sym_notebook_code_cell_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_language_markdown] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_markdown_text_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_PERCENT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_language_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_notebook_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_notebook_markdown_cell] = {
    .visible = true,
    .named = true,
  },
  [sym__markdown_block] = {
    .visible = false,
    .named = true,
  },
  [sym_markdown_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_fenced_block] = {
    .visible = true,
    .named = true,
  },
  [sym_notebook_code_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_code_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_notebook_markdown_cell_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markdown_fenced_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_notebook_code_cell_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_fence_close = 1,
  field_fence_open = 2,
  field_lang = 3,
  field_marker = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_fence_close] = "fence_close",
  [field_fence_open] = "fence_open",
  [field_lang] = "lang",
  [field_marker] = "marker",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_marker, 0},
  [1] =
    {field_lang, 1},
    {field_marker, 0},
  [3] =
    {field_fence_close, 2},
    {field_fence_open, 0},
  [5] =
    {field_fence_close, 3},
    {field_fence_open, 0},
  [7] =
    {field_fence_close, 3},
    {field_fence_open, 0},
    {field_lang, 1},
  [10] =
    {field_fence_close, 4},
    {field_fence_open, 0},
    {field_lang, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == '`') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '`') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '[') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '[') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(30);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(46);
      if (lookahead == 'a') ADVANCE(10);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == ']') ADVANCE(46);
      if (lookahead == 'd') ADVANCE(9);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == ']') ADVANCE(46);
      if (lookahead == 'k') ADVANCE(6);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == ']') ADVANCE(46);
      if (lookahead == 'n') ADVANCE(14);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == ']') ADVANCE(46);
      if (lookahead == 'o') ADVANCE(11);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == ']') ADVANCE(46);
      if (lookahead == 'r') ADVANCE(7);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == ']') ADVANCE(46);
      if (lookahead == 'w') ADVANCE(8);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == ']') ADVANCE(46);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == ']') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == '`') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == '`') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'k') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(5);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 25:
      if (lookahead == 'w') ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 27:
      if (eof) ADVANCE(29);
      if (lookahead == '\n') SKIP(27);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '`') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      if (lookahead == '\n') SKIP(28);
      if (lookahead == '#') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_POUND_PERCENT);
      if (lookahead == '%') ADVANCE(44);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_POUND_PERCENT);
      if (lookahead == '%') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_language_markdown);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_markdown_text_line_token1);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '`') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_markdown_text_line_token1);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '`') ADVANCE(40);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_markdown_text_line_token1);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(41);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_markdown_text_line_token1);
      if (lookahead == '%') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_markdown_text_line_token1);
      if (lookahead == '`') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_markdown_text_line_token1);
      if (lookahead == '`') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_markdown_text_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_POUND_PERCENT_PERCENT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_POUND_PERCENT_PERCENT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_language_tag);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 27},
  [3] = {.lex_state = 27},
  [4] = {.lex_state = 27},
  [5] = {.lex_state = 27},
  [6] = {.lex_state = 27},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 28},
  [10] = {.lex_state = 28},
  [11] = {.lex_state = 28},
  [12] = {.lex_state = 28},
  [13] = {.lex_state = 28},
  [14] = {.lex_state = 27},
  [15] = {.lex_state = 27},
  [16] = {.lex_state = 27},
  [17] = {.lex_state = 27},
  [18] = {.lex_state = 27},
  [19] = {.lex_state = 28},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND_PERCENT] = ACTIONS(1),
    [sym_language_markdown] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [anon_sym_POUND_PERCENT_PERCENT] = ACTIONS(1),
    [sym_language_tag] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(32),
    [sym_notebook_cell] = STATE(7),
    [sym_notebook_markdown_cell] = STATE(25),
    [sym_notebook_code_cell] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND_PERCENT] = ACTIONS(5),
    [anon_sym_POUND_PERCENT_PERCENT] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      aux_sym_markdown_text_line_token1,
    ACTIONS(15), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(11), 2,
      anon_sym_POUND_PERCENT,
      anon_sym_POUND_PERCENT_PERCENT,
    STATE(5), 4,
      sym__markdown_block,
      sym_markdown_text_line,
      sym_markdown_fenced_block,
      aux_sym_notebook_markdown_cell_repeat1,
  [20] = 5,
    ACTIONS(13), 1,
      aux_sym_markdown_text_line_token1,
    ACTIONS(15), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 2,
      anon_sym_POUND_PERCENT,
      anon_sym_POUND_PERCENT_PERCENT,
    STATE(6), 4,
      sym__markdown_block,
      sym_markdown_text_line,
      sym_markdown_fenced_block,
      aux_sym_notebook_markdown_cell_repeat1,
  [40] = 5,
    ACTIONS(13), 1,
      aux_sym_markdown_text_line_token1,
    ACTIONS(15), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 2,
      anon_sym_POUND_PERCENT,
      anon_sym_POUND_PERCENT_PERCENT,
    STATE(2), 4,
      sym__markdown_block,
      sym_markdown_text_line,
      sym_markdown_fenced_block,
      aux_sym_notebook_markdown_cell_repeat1,
  [60] = 5,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      aux_sym_markdown_text_line_token1,
    ACTIONS(32), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(27), 2,
      anon_sym_POUND_PERCENT,
      anon_sym_POUND_PERCENT_PERCENT,
    STATE(5), 4,
      sym__markdown_block,
      sym_markdown_text_line,
      sym_markdown_fenced_block,
      aux_sym_notebook_markdown_cell_repeat1,
  [80] = 5,
    ACTIONS(13), 1,
      aux_sym_markdown_text_line_token1,
    ACTIONS(15), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 2,
      anon_sym_POUND_PERCENT,
      anon_sym_POUND_PERCENT_PERCENT,
    STATE(5), 4,
      sym__markdown_block,
      sym_markdown_text_line,
      sym_markdown_fenced_block,
      aux_sym_notebook_markdown_cell_repeat1,
  [100] = 5,
    ACTIONS(5), 1,
      anon_sym_POUND_PERCENT,
    ACTIONS(7), 1,
      anon_sym_POUND_PERCENT_PERCENT,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(8), 2,
      sym_notebook_cell,
      aux_sym_source_file_repeat1,
    STATE(25), 2,
      sym_notebook_markdown_cell,
      sym_notebook_code_cell,
  [118] = 5,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      anon_sym_POUND_PERCENT,
    ACTIONS(46), 1,
      anon_sym_POUND_PERCENT_PERCENT,
    STATE(8), 2,
      sym_notebook_cell,
      aux_sym_source_file_repeat1,
    STATE(25), 2,
      sym_notebook_markdown_cell,
      sym_notebook_code_cell,
  [136] = 4,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      aux_sym_markdown_text_line_token1,
    ACTIONS(51), 2,
      anon_sym_POUND_PERCENT,
      anon_sym_POUND_PERCENT_PERCENT,
    STATE(10), 2,
      sym_raw_code_line,
      aux_sym_notebook_code_cell_repeat1,
  [151] = 4,
    ACTIONS(53), 1,
      aux_sym_markdown_text_line_token1,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 2,
      anon_sym_POUND_PERCENT,
      anon_sym_POUND_PERCENT_PERCENT,
    STATE(12), 2,
      sym_raw_code_line,
      aux_sym_notebook_code_cell_repeat1,
  [166] = 4,
    ACTIONS(53), 1,
      aux_sym_markdown_text_line_token1,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 2,
      anon_sym_POUND_PERCENT,
      anon_sym_POUND_PERCENT_PERCENT,
    STATE(13), 2,
      sym_raw_code_line,
      aux_sym_notebook_code_cell_repeat1,
  [181] = 4,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      aux_sym_markdown_text_line_token1,
    ACTIONS(65), 2,
      anon_sym_POUND_PERCENT,
      anon_sym_POUND_PERCENT_PERCENT,
    STATE(12), 2,
      sym_raw_code_line,
      aux_sym_notebook_code_cell_repeat1,
  [196] = 4,
    ACTIONS(53), 1,
      aux_sym_markdown_text_line_token1,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 2,
      anon_sym_POUND_PERCENT,
      anon_sym_POUND_PERCENT_PERCENT,
    STATE(12), 2,
      sym_raw_code_line,
      aux_sym_notebook_code_cell_repeat1,
  [211] = 2,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 4,
      anon_sym_POUND_PERCENT,
      aux_sym_markdown_text_line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND_PERCENT_PERCENT,
  [221] = 2,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 4,
      anon_sym_POUND_PERCENT,
      aux_sym_markdown_text_line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND_PERCENT_PERCENT,
  [231] = 2,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 4,
      anon_sym_POUND_PERCENT,
      aux_sym_markdown_text_line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND_PERCENT_PERCENT,
  [241] = 2,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 4,
      anon_sym_POUND_PERCENT,
      aux_sym_markdown_text_line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND_PERCENT_PERCENT,
  [251] = 2,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 4,
      anon_sym_POUND_PERCENT,
      aux_sym_markdown_text_line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND_PERCENT_PERCENT,
  [261] = 2,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 3,
      anon_sym_POUND_PERCENT,
      aux_sym_markdown_text_line_token1,
      anon_sym_POUND_PERCENT_PERCENT,
  [270] = 3,
    ACTIONS(100), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(23), 1,
      aux_sym_markdown_fenced_block_repeat1,
    ACTIONS(98), 2,
      anon_sym_LF,
      aux_sym_markdown_text_line_token1,
  [281] = 3,
    ACTIONS(105), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(21), 1,
      aux_sym_markdown_fenced_block_repeat1,
    ACTIONS(102), 2,
      anon_sym_LF,
      aux_sym_markdown_text_line_token1,
  [292] = 3,
    ACTIONS(109), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(24), 1,
      aux_sym_markdown_fenced_block_repeat1,
    ACTIONS(107), 2,
      anon_sym_LF,
      aux_sym_markdown_text_line_token1,
  [303] = 3,
    ACTIONS(113), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(21), 1,
      aux_sym_markdown_fenced_block_repeat1,
    ACTIONS(111), 2,
      anon_sym_LF,
      aux_sym_markdown_text_line_token1,
  [314] = 3,
    ACTIONS(115), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(21), 1,
      aux_sym_markdown_fenced_block_repeat1,
    ACTIONS(111), 2,
      anon_sym_LF,
      aux_sym_markdown_text_line_token1,
  [325] = 2,
    ACTIONS(119), 1,
      anon_sym_POUND_PERCENT,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_PERCENT_PERCENT,
  [333] = 2,
    ACTIONS(121), 1,
      anon_sym_LF,
    ACTIONS(123), 1,
      sym_language_tag,
  [340] = 2,
    ACTIONS(125), 1,
      anon_sym_LF,
    ACTIONS(127), 1,
      sym_language_tag,
  [347] = 2,
    ACTIONS(129), 1,
      anon_sym_LF,
    ACTIONS(131), 1,
      sym_language_markdown,
  [354] = 1,
    ACTIONS(133), 1,
      anon_sym_LF,
  [358] = 1,
    ACTIONS(135), 1,
      anon_sym_LF,
  [362] = 1,
    ACTIONS(137), 1,
      anon_sym_LF,
  [366] = 1,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 60,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 100,
  [SMALL_STATE(8)] = 118,
  [SMALL_STATE(9)] = 136,
  [SMALL_STATE(10)] = 151,
  [SMALL_STATE(11)] = 166,
  [SMALL_STATE(12)] = 181,
  [SMALL_STATE(13)] = 196,
  [SMALL_STATE(14)] = 211,
  [SMALL_STATE(15)] = 221,
  [SMALL_STATE(16)] = 231,
  [SMALL_STATE(17)] = 241,
  [SMALL_STATE(18)] = 251,
  [SMALL_STATE(19)] = 261,
  [SMALL_STATE(20)] = 270,
  [SMALL_STATE(21)] = 281,
  [SMALL_STATE(22)] = 292,
  [SMALL_STATE(23)] = 303,
  [SMALL_STATE(24)] = 314,
  [SMALL_STATE(25)] = 325,
  [SMALL_STATE(26)] = 333,
  [SMALL_STATE(27)] = 340,
  [SMALL_STATE(28)] = 347,
  [SMALL_STATE(29)] = 354,
  [SMALL_STATE(30)] = 358,
  [SMALL_STATE(31)] = 362,
  [SMALL_STATE(32)] = 366,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notebook_markdown_cell, 4, 0, 2),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_notebook_markdown_cell, 4, 0, 2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notebook_markdown_cell, 2, 0, 1),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_notebook_markdown_cell, 2, 0, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notebook_markdown_cell, 3, 0, 2),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_notebook_markdown_cell, 3, 0, 2),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_notebook_markdown_cell_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_notebook_markdown_cell_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_notebook_markdown_cell_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_notebook_markdown_cell_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notebook_markdown_cell, 3, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_notebook_markdown_cell, 3, 0, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notebook_code_cell, 2, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_notebook_code_cell, 2, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notebook_code_cell, 3, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_notebook_code_cell, 3, 0, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notebook_code_cell, 3, 0, 2),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_notebook_code_cell, 3, 0, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_notebook_code_cell_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_notebook_code_cell_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_notebook_code_cell_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notebook_code_cell, 4, 0, 2),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_notebook_code_cell, 4, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_fenced_block, 4, 0, 4),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_fenced_block, 4, 0, 4),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_text_line, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_text_line, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_fenced_block, 5, 0, 6),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_fenced_block, 5, 0, 6),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_fenced_block, 3, 0, 3),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_fenced_block, 3, 0, 3),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_fenced_block, 4, 0, 5),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_fenced_block, 4, 0, 5),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_code_line, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_code_line, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markdown_fenced_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_markdown_fenced_block_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notebook_cell, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_notebook_cell, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [139] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fknb(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fknb",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
